### ISSUE TITLE
metadata is missing from ProductsGetResponse

### ISSUE THREAD

**Issue by salzhrani** [voucherifyio/voucherify-js-sdk#133]
Good day,
the `metadata` property is missing from `ProductsGetResponse` type although it is return from the the `/v1/products` endpoint
would love to send PR if it is just a simple adding of the property

**Comment by darekg11** [comment]
Hello @salzhrani, I am one of the maintainers of this SDK.
Thank you for your interest in helping out, it's much appreciated.

And yes you are correct, you just need to add:
```
metadata?: Record<string, any>
```
property definition to: https://github.com/voucherifyio/voucherify-js-sdk/blob/7ae2f44d17ecd99b0bdef6d31588c9f7cf1b135d/packages/sdk/src/types/Products.ts#L18

since `ProductsGetResponse` is made of `ProductsCreateResponse & ProductsGetResponseSkus`

I will be happy to review your Pull Request and release new version after merging.
Just make sure to check out or contribution guide: https://github.com/voucherifyio/voucherify-js-sdk/blob/main/CONTRIBUTING.md

**Comment by salzhrani** [comment]
[darekg11](https://github.com/darekg11) PR created, please review at your leisure

**Comment by darekg11** [comment]
@salzhrani thank you for your contribution.
I just released a new version - `2.0.10` - it should be shortly available in the NPM registry.
