### ISSUE TITLE
Is react-native available?

### ISSUE THREAD

**Issue by musesfish** [voucherifyio/voucherify-js-sdk#159]
Is this sdk suitable for react-native mobile projects?
If it doesn't fit, is there other sdk suitable for react-native projects.
Looking forward to your answer.

**Comment by darekg11** [comment]
Yes, it should work but we do not recommend using it in react-native app, that is because react-native app is essentially packed and available on the end-user mobile device. Because of that an attack party might reverse-engineer the mobile app and extract API Keys pair that are essential to establish connection with Voucherify API.

Recommended approach by us is to use Server-Side API on your own backend server and only establish connection from our mobile app to your backend server which is then calling Voucherify API making all API Keys hidden from end-user.

**Comment by musesfish** [comment]
> Yes, it should work but we do not recommend using it in react-native app, that is because react-native app is essentially packed and available on the end-user mobile device. Because of that an attack party might reverse-engineer the mobile app and extract API Keys pair that are essential to establish connection with Voucherify API.
> 
> Recommended approach by us is to use Server-Side API on your own backend server and only establish connection from your mobile app to your backend server which is then calling Voucherify API making all API Keys hidden from end-user.
> 
> Please let me know if this answers resolves your issue. In case of no response, this issue will be closed in 7 days.
-----------------------------------------------------------------------------------------------------------------------------------------Thanks for your answer, it worked for me.
