### ISSUE TITLE
Is it possible to use Voucherify js SDK in Angular apps ?

### ISSUE THREAD

**Issue by evandersar** [voucherifyio/voucherify-js-sdk#185]

**Comment by darekg11** [comment]
It should be, but we do not recommend it since using SDK in Angular App would mean exposing your Voucherify API Keys to end-users.
We are recommending using Voucherify SDK on your backend services behind some kind of authentication.
If you really wish to use this SDK on front-end, then you should use:
```
const { VoucherifyClientSide } = require('@voucherify/sdk')
```
and use client side API Key pairs
