### ISSUE TITLE
"promotion_tier" field does not appear in RedemptionsRedeemResponse

### ISSUE THREAD

**Issue by redjolr** [voucherifyio/voucherify-js-sdk#194]
Hello,

We have a feature where we need the "promotion_tier" in the response of 
```typescript
redemptions.redeemStackable(p: RedemptionsRedeemStackableParams): Promise<RedemptionsRedeemStackableResponse>
```
Im taking about RedemptionsRedeemStackableResponse interface defined here: https://github.com/voucherifyio/voucherify-js-sdk/blob/main/packages/sdk/src/types/Redemptions.ts

There should be a "promotion_tier" on the type `RedemptionsRedeemStackableResponse.redemptions[]`. Please, this is very important for us.

Can you guys please expose this field?

**Comment by darekg11** [comment]
Hello @redjolr, this will be done on Monday including new patch version release (I will also fix https://github.com/voucherifyio/voucherify-js-sdk/issues/193)

**Comment by darekg11** [comment]
Dear @redjolr new version of SDK `2.1.8` has just been released and should be available in NPM registry shortly.
This release contains fix fot your issue.
Related changes: https://github.com/voucherifyio/voucherify-js-sdk/pull/195
Related PR that triggered release: https://github.com/voucherifyio/voucherify-js-sdk/pull/196

Because returned object might be different depending if you are passing `expand` optiions to stackable redemption endpoint then `promotion_tier` definition might be different. This is the reason why there is union of two types for that property and you must explicitly  cast to appropriate type depending on your request.

I am going to close this issue, please freel free to re-open if you feel like it
